const data = [{
    itemName: "IF - John Krasinski",
    itemCategory: "2024",
    itemLink: "https://www.youtube.com/watch?v=el0N_MDcp0Y",
    itemCopy: "A STORY YOU HAVE TO BELIEVE TO SEE. A girl discovers she can see everyone’s imaginary friends and embarks on a magical adventure to reconnect forgotten IFs with their kids.",
    itemImg: "src/assets/if.jpg",
},
{
    itemName: "The Holdovers - Alexander Payne",
    itemCategory: "2023",
    itemLink: "https://www.youtube.com/watch?v=AhKLpJmHhIg",
    itemCopy: "A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break to babysit the handful of students with nowhere to go. Eventually, he forms an unlikely bond with one of them — a damaged, brainy troublemaker — and with the school’s head cook, who has just lost a son in Vietnam.",
    itemImg: "src/assets/Holdovers.jpg",
},
{
    itemName: "Fallen Leaves - Aki Kaurismäki",
    itemCategory: "2023",
    itemLink: "https://www.youtube.com/watch?v=a7n8IXlIcS4",
    itemCopy: "The film tells the story of Ansa, a supermarket shelf-stocker on a zero-hour contract, later a recyclable plastic sorter, and Holappa, a sandblaster, an alcoholic, later an ex-alcoholic, whose paths have accidentally crossed and who, despite adversity and misunderstandings, try to build some kind of relationship on the harsher side of the welfare state.",
    itemImg: "src/assets/fallen.jpg",
},
{
    itemName: "The Fabelmans - Steven Spielberg",
    itemCategory: "2022",
    itemLink: "https://www.youtube.com/watch?v=9wAKUa487aw",
    itemCopy: "CAPTURE EVERY MOMENT. A coming-of-age story about a young man’s discovery of a shattering family secret and an exploration of the power of movies to help us see the truth about each other and ourselves.",
    itemImg: "src/assets/fabelmans.jpg",
},
{
    itemName: "As bestas - Rodrigo Sorogoyen",
    itemCategory: "2022",
    itemLink: "https://www.youtube.com/watch?v=aoR5_TVASXU",
    itemCopy: "Antoine and Olga, a French couple, have been living in a small village in Galicia for a long time. They practice eco-responsible agriculture and restore abandoned houses to facilitate repopulation. Everything should be idyllic but for their opposition to a wind turbine project that creates a serious conflict with their neighbors. The tension will rise to the point of irreparability.",
    itemImg: "src/assets/as-bestas.jpg",
},
{
    itemName: "Dark Glasses - Dario Argento",
    itemCategory: "2022",
    itemLink: "https://www.youtube.com/watch?v=uplxZ9JiA1o",
    itemCopy: "TO WAKE UP FROM THIS NIGHTMARE, YOU WON’T BE ABLE TO OPEN YOUR EYES. Diana, a high-class prostitute trying to escape from a serial killer, suffers a car accident that leaves her blind and kills the family of Chin, a ten-year-old boy.",
    itemImg: "src/assets/dark-glasses.jpg",
},
{
    itemName: "Licorice Pizza - Paul Thomas Anderson",
    itemCategory: "2021",
    itemLink: "https://www.youtube.com/watch?v=ofnXPwUPENo",
    itemCopy: "Set in the San Fernando Valley in the 1970s, the film follows a high school student who is also a successful child actor.",
    itemImg: "src/assets/licorice-pizza.jpg",
},
{
    itemName: "Cry Macho - Clint Eastwood",
    itemCategory: "2021",
    itemLink: "https://www.youtube.com/watch?v=JVc8SI5CAKw",
    itemCopy: "A STORY OF BEING LOST… AND FOUND. Mike Milo, a one-time rodeo star and washed-up horse breeder, takes a job from an ex-boss to bring the man’s young son home from Mexico.",
    itemImg: "src/assets/cry-macho.jpg",
},
{
    itemName: "The Hunt - Craig Zobel",
    itemCategory: "2020",
    itemLink: "https://www.youtube.com/watch?v=R8AcWtwJM-g",
    itemCopy: "THE ULTIMATE HUMAN HUNTING EXPERIENCE. Twelve strangers wake up in a clearing. They don’t know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
    itemImg: "src/assets/the-hunt.jpg",
},
{
    itemName: "Palm Springs - Max Barbakow",
    itemCategory: "2020",
    itemLink: "https://www.youtube.com/watch?v=CpBLtXduh_k",
    itemCopy: "When carefree Nyles and reluctant maid of honor Sarah have a chance encounter at a Palm Springs wedding, things get complicated as they are unable to escape the venue, themselves, or each other.",
    itemImg: "src/assets/palm-spring.jpg",
},
{
    itemName: "Once Upon a Time… in Hollywood - Quentin Tarantino",
    itemCategory: "2019",
    itemLink: "https://www.youtube.com/watch?v=ELeMaP8EPAA",
    itemCopy: "IN THIS TOWN, IT CAN ALL CHANGE… LIKE THAT Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
    itemImg: "src/assets/once.jpg",
},
{
    itemName: "The Irishman -  Martin Scorsese",
    itemCategory: "2019",
    itemLink: "https://www.youtube.com/watch?v=RS3aHkkfuEI",
    itemCopy: "HIS STORY CHANGED HISTORY Pennsylvania, 1956. Frank Sheeran, a war veteran of Irish origin who works as a truck driver, accidentally meets mobster Russell Bufalino. Once Frank becomes his trusted man, Bufalino sends him to Chicago with the task of helping Jimmy Hoffa, a powerful union leader related to organized crime, with whom Frank will maintain a close friendship for nearly twenty years.",
    itemImg: "src/assets/irish.jpg",
},
{
    itemName: "Ford v Ferrari - James Mangold",
    itemCategory: "2019",
    itemLink: "https://www.youtube.com/watch?v=I3h9Z89U9ZA",
    itemCopy: "THEY TOOK THE AMERICAN DREAM FOR A RIDE American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.",
    itemImg: "src/assets/fvf.jpg",
},
{
    itemName: "Burning -  Lee Chang-dong",
    itemCategory: "2018",
    itemLink: "https://www.youtube.com/watch?v=oihHs2Errwk",
    itemCopy: "THE TRUTH IS ALL IN YOUR HEAD. Deliveryman Jongsu is out on a job when he runs into Haemi, a girl who once lived in his neighborhood. She asks if he’d mind looking after her cat while she’s away on a trip to Africa. On her return she introduces to Jongsu an enigmatic young man named Ben, who she met during her trip. And one day Ben tells Jongsu about his most unusual hobby…",
    itemImg: "src/assets/burning.jpg",
},
{
    itemName: "Never Look Away - Florian Henckel von Donnersmarck",
    itemCategory: "2018",
    itemLink: "https://www.youtube.com/watch?v=gCEYXnDNcrg",
    itemCopy: "The story of Kurt, a young art student who falls in love with fellow student, Ellie. Ellie’s father, Professor Seeband, a famous doctor, is dismayed at his daughter’s choice of boyfriend, and vows to destroy the relationship. What neither of them knows is that their lives are already connected through a terrible crime Seeband committed decades ago.",
    itemImg: "src/assets/never-look-away.jpg",
},
{
    itemName: "Ready Player One - Steven Spielberg",
    itemCategory: "2018",
    itemLink: "https://www.youtube.com/watch?v=1hrwbc5qCZ4",
    itemCopy: "A BETTER REALITY AWAITS. When the creator of a popular video game system dies, a virtual contest is created to compete for his fortune.",
    itemImg: "src/assets/ready-p.jpg",
},
{
    itemName: "Phantom Thread -  Paul Thomas Anderson",
    itemCategory: "2017",
    itemLink: "https://www.youtube.com/watch?v=xNsiQMeSvMk",
    itemCopy: "Renowned British dressmaker Reynolds Woodcock comes across Alma, a young, strong-willed woman, who soon becomes a fixture in his life as his muse and lover.",
    itemImg: "src/assets/phantom.jpg",
},
{
    itemName: "Logan -  James Mangold   ",
    itemCategory: "2017",
    itemLink: "https://www.youtube.com/watch?v=XaE_9pfybL4",
    itemCopy: "HIS TIME HAS COME In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan’s attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
    itemImg: "src/assets/logan.jpg",
},
{
    itemName: "Split -  M. Night Shyamalan",
    itemCategory: "2016",
    itemLink: "https://www.youtube.com/watch?v=6bfooooTKyM",
    itemCopy: "KEVIN HAS 23 DISTINCT PERSONALITIES. THE 24TH IS ABOUT TO BE UNLEASHED.  Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.",
    itemImg: "src/assets/split.jpg",
},
{
    itemName: "La La Land - Damien Chazelle",
    itemCategory: "2016",
    itemLink: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    itemCopy: "HERE’S TO THE FOOLS WHO DREAM. Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    itemImg: "src/assets/land.jpg",
},
{
    itemName: "Two Lovers - James Gray",
    itemCategory: "2008",
    itemLink: "https://www.youtube.com/watch?v=8xpmtjOsysM",
    itemCopy: "SOMETIMES WE LEAVE EVERYTHING TO FIND OURSELVES. A depressed man moves back in with his parents following a recent heartbreak and finds himself with two women.",
    itemImg: "src/assets/two-lovers.jpg",
},
{
    itemName: "Chungking Express -  Wong Kar-wai",
    itemCategory: "1994",
    itemLink: "https://www.youtube.com/watch?v=OPCug9jyG9k",
    itemCopy: "WHAT A DIFFERENCE A DAY MAKES Two melancholic Hong Kong policemen fall in love: one with a mysterious underworld figure, the other with a beautiful and ethereal server at a late-night restaurant he frequents.",
    itemImg: "src/assets/express.jpg",
},
{
    itemName: "No Country for Old Men -  Joel Coen, Ethan Coen",
    itemCategory: "2007",
    itemLink: "https://www.youtube.com/watch?v=38A__WT3-o0",
    itemCopy: "THERE ARE NO CLEAN GETAWAYS. Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.",
    itemImg: "src/assets/old-men.jpg",
},
{
    itemName: "Basic Instinct -  Paul Verhoeven",
    itemCategory: "1992",
    itemLink: "https://www.youtube.com/watch?v=HL-eEzcSU3w",
    itemCopy: "A BRUTAL MURDER. A BRILLIANT KILLER. A COP WHO CAN’T RESIST THE DANGER. A police detective is in charge of the investigation of a brutal murder, in which a beautiful and seductive woman could be involved.",
    itemImg: "src/assets/basic.jpg",
},
{
    itemName: "Midnight in Paris - Woody Allen",
    itemCategory: "2011",
    itemLink: "https://www.youtube.com/watch?v=FAfR8omt-CY",
    itemCopy: "A romantic comedy about a family traveling to the French capital for business. The party includes a young engaged couple forced to confront the illusion that a life different from their own is better.",
    itemImg: "src/assets/paris.jpg",
},
{
    itemName: "Heat -  Michael Mann",
    itemCategory: "1995",
    itemLink: "https://www.youtube.com/watch?v=q0tUj2_eTn0",
    itemCopy: "WA LOS ANGELES CRIME SAGA. Obsessive master thief Neil McCauley leads a top-notch crew on various daring heists throughout Los Angeles while determined detective Vincent Hanna pursues him without rest. Each man recognizes and respects the ability and the dedication of the other even though they are aware their cat-and-mouse game may end in violence.",
    itemImg: "src/assets/heat.jpg",
},
{
    itemName: "The Wolf of Wall Street - Martin Scorsese",
    itemCategory: "2013",
    itemLink: "https://www.youtube.com/watch?v=Slj4-Sv-YNA",
    itemCopy: "EARN. SPEND. PARTY. A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort’s autobiography.",
    itemImg: "src/assets/wolf.jpg",
},
{
    itemName: "Rear Window -  Alfred Hitchcock",
    itemCategory: "1954",
    itemLink: "https://www.youtube.com/watch?v=R1Av5y_VUdQ",
    itemCopy: "IT ONLY TAKES ONE WITNESS TO SPOIL THE PERFECT CRIME. Professional photographer L.B. ‘Jeff’ Jeffries breaks his leg while getting an action shot at an auto race. Confined to his New York apartment, he spends his time looking out of the rear window observing the neighbors. When he begins to suspect that a man across the courtyard may have murdered his wife, Jeff enlists the help of his high society fashion-consultant girlfriend and his visiting nurse to investigate.",
    itemImg: "src/assets/rear.jpg",
},
{
    itemName: "The Greatest Showman - Michael Gracey",
    itemCategory: "2017",
    itemLink: "https://www.youtube.com/watch?v=jr9QtXwC9vc",
    itemCopy: "THE IMPOSSIBLE COMES TRUE The story of American showman P.T. Barnum, founder of the circus that became the famous traveling Ringling Bros. and Barnum & Bailey Circus.",
    itemImg: "src/assets/showman.jpg",
},
{
    itemName: "Blow Out -  Brian De Palma",
    itemCategory: "1981",
    itemLink: "https://www.youtube.com/watch?v=6L0leO_Fw_U",
    itemCopy: "MURDER HAS A SOUND ALL OF ITS OWN! Jack Terry is a master sound recordist who works on grade-B horror movies. Late one evening, he is recording sounds for use in his movies when he hears something unexpected through his sound equipment and records it. Curiosity gets the better of him when the media become involved, and he begins to unravel the pieces of a nefarious conspiracy. As he struggles to survive against his shadowy enemies and expose the truth, he does not know whom he can trust.",
    itemImg: "src/assets/blow-out.jpg",
},
]

export { data }